### PR TITLE
query params from template, layer, locale, or workspace

### PR DESCRIPTION
**Pull request by dbauszus-glx**
For security reasons the dbs should not be provided as a request parameter.

Any references to the dbs request parameter have been removed from the mapp library in this PR.

The layer.dbs will be set to the locale.dbs which will be set to the workspace.dbs.

The layer.dbs or workspace.dbs will be used as fallback if the template object has no dbs property.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208538873788583

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
The layer parameter should always be provided if available.

**Comment by simon-leech** [comment]
This is working for me

Note when testing: 
Queries that are ran in custom_views that don't use the workspace.dbs will need the layer and locale providing as params to use that dbs

**Review by simon-leech — APPROVED** [review]

**Comment by simon-leech** [comment]
Also please don't merge until @RobAndrewHurst  has had a look after his hols!

**Review by RobAndrewHurst — APPROVED** [review]
Updated the tests, and I am all happy with these changes.

**Pull request merged**
