### PR TITLE
Update sqlFilter mod

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
## Description

https://github.com/GEOLYTIX/xyz/security/code-scanning/208

### CODE REVIEW

**Review by AlexanderGeere — APPROVED** [review]
Lgtm

**Review by simon-leech — APPROVED** [review]

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
Is there a test case for the filter?

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
I updated the isValid description.

image

What about integer? Are integer always typeof bigint?

Would an object ever be a valid value? I can not think about a filter where an object would be valid?

How can I make the test fail?

Let's say I provide 'foo' string as a value for a numeric filter check. String is valid type but the filter crashes.

The type should be provided for the test. Ie. I add a value for an integer filter then type must be int or bigint. I add a value for a numeric filter then value must be numeric.

**Comment by RobAndrewHurst** [comment]
> I updated the isValid description.
> 
> image
> 
> What about integer? Are integer always typeof bigint?
> 
> Would an object ever be a valid value? I can not think about a filter where an object would be valid?
> 
> How can I make the test fail?
> 
> Let's say I provide 'foo' string as a value for a numeric filter check. String is valid type but the filter crashes.

Good question about the types. 

We appear to get an array of params as a param when using ni or in filters. So the type of object would be valid.

Doesn't number cover integers and floats?

**Comment by RobAndrewHurst** [comment]
image

**Comment by dbauszus-glx** [comment]
I would expect something like this?

https://github.com/GEOLYTIX/xyz/pull/1510/commits/8edd8400cafcaca5e18874195294cab6e386901f

If addValue numeric then test for number, if string test for string, if array then test for array.

**Review by dbauszus-glx — APPROVED** [review]
This is working for me.

I added a check on the error to not execute the query.

https://github.com/GEOLYTIX/xyz/pull/1510/commits/07de3c3c83d6215e5343a50fef4f9675304a2627

Error is logged in process console.
image

And returned to client.
image

**Pull request merged**
