### PR TITLE
Layer View: Layer / Layer Group distinction

### PR DESCRIPTION
**Pull request by AlexanderGeere**
## Description

Added css so layer headers and layer headers inside groups so they appear less bold than group headers.

Before:
Screenshot 2024-11-12 151136

After:
Screenshot 2024-11-12 144415

## GitHub Issue
#1704 

## Type of Change
- ✅ New feature (non-breaking change which adds functionality)

## How have you tested this? 
Can be tested on layer with groups. I have tested it on `bugs_testing/ui_elements/workspace.json`.

## Testing Checklist 
- ✅ Existing Tests still pass
- ✅ Ran locally on my machine

## Code Quality Checklist
- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by simon-leech — APPROVED** [review]
I really like this UI change, the distinction is now immediately apparent! nice work 😅

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
I don't think the css checks for any h2 are necessary. Only checks for h2 in header.

An empty drawer layer view will still have a header with the h2 nested in the header. 
image

**Comment by AlexanderGeere** [comment]
> I don't think the css checks for any h2 are necessary. Only checks for h2 in header.
> 
> An empty drawer layer view will still have a header with the h2 nested in the header. image

Check [1cf7c03](https://github.com/GEOLYTIX/xyz/pull/1705/commits/1cf7c03096126d0716fe3453a351bbe2f847c54b), I changed to only check for h2's inside headers.

**Comment by dbauszus-glx** [comment]
If the layer view header should be rendered normal but not the layer-group header then the rule for the layer-group header can be removed.

I nested the header rule for layer-view in the existing layer-view block.

https://github.com/GEOLYTIX/xyz/pull/1705/commits/b44e3e6ae296c1a3ab92bd1468793430985a4561

**Review by dbauszus-glx — APPROVED** [review]

**Review by RobAndrewHurst — APPROVED** [review]

**Pull request merged**
