### PR TITLE
fixed dropdown issue on mobile

### PR DESCRIPTION
**Pull request by eo-uk**
Fixed the issue where dropdown items would not display on mobile. Dropdowns under tabview require fixed position whereas ones under the side panel need absolute position.

### CODE REVIEW

**Review by RobAndrewHurst — CHANGES_REQUESTED** [review]
Shouldn't this change include changes to the sass file too, not just to the bundled css

**Comment by eo-uk** [comment]
Right, missed those. Added them now.

**Comment by RobAndrewHurst** [comment]
> 

Nice! I also just pushed the changes!

**Review by RobAndrewHurst — APPROVED** [review]
Awesome! Looks good to me!

**Pull request merged**
