### PR TITLE
Filter panel: reset all function

### PR DESCRIPTION
**Pull request by AlexanderGeere**
## Description
Adds the ability to reset the filters back to their starting positions.

Reset all will leave the filter in the dom, but just remove any user provided input and clear the parameters from the filter. 

## GitHub Issue

[#1566](https://github.com/GEOLYTIX/xyz/issues/1566)

## Type of Change
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Documentation

## How have you tested this? 
Tested on the demo multi_filter.  Can be tested on `bugs_testing/filter/all_filters.json`. To test the multi_filter please use the PR.
(The multi filter is present on `bugs_testing/filter/all_filters.json`)

## Testing Checklist 
- ✅ Existing Tests still pass
- ✅ Ran locally on my machine

## Code Quality Checklist
- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208550579293270

### CODE REVIEW

**Review by simon-leech — CHANGES_REQUESTED** [review]
I noticed we use the same styling `margin-bottom: 5px;text-decoration: underline` for both buttons. 
Can we move that to a class to be accessible for other elements too? 

Would you be able to write a test for this too so we can confirm its working as expected?

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/pull/1567/commits/ca7a70418ebb8ca3a809d734bd76b5ec10ef6d6c

Instead of altering the filter on reset it is much easier to delete the filter and replace the card.

The delete filter has been moved into a method to avoid code duplication with removeFilter method.

The docs have been updated as only the deleteFilter method needs to know the filter properties and remove / reset just need to know the html elements.

The card element had to be updated. The card cannot be assigned to the properties. This would make replacing the element impossible.

**Review by dbauszus-glx — APPROVED** [review]
Looks good to me. But I also did a few changes so this must be reviewed by someone else in detail.

**Review by RobAndrewHurst — APPROVED** [review]
Happy with this!

**Pull request merged**
