### PR TITLE
added flexbox css to map legend

### PR DESCRIPTION
**Pull request by eo-uk**
Added css rules to optionally make legends use flexbox instead of grid.

### CODE REVIEW

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
Can you apply this to the legend script?

Ideally I would like the container to be a flex class element. This could be returned by an element util to which you provide an array of elements are argument with options to control the flex behaviour, e.g. the direction.

We want to get away from a legend being grid or flex. But a grid container being grid, and a flex container being flex. And a legend can choose which class container to use.

**Review by simon-leech — APPROVED** [review]
I've tested this in both layer config and also in legends for custom views and working as expected 👍

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
lib/ui/layers/panels/style.mjs

You don't need to overload the call to the legend method. The layer is provided as first argument, all members of the layer such as style.theme.legendOptions can be accessed in the legend method without the additional argument.

lib/ui/layers/legends/categorized.mjs

Instead of the legendOptions argument you can access these from the layer. layer.style.theme.legendOptions. These don't need to be optional since the method would not be called without the layer having a style.theme configuration.

We don't want to have clashing classes.

The container should either be `.grid` or `.flex`. But not `.grid.flex`

`.grid` inside `.flex` or vice versa is fine.

image

**Comment by dbauszus-glx** [comment]
Changed `type` to `layout` and `alignContent:'center'` to `alignContent:'centered'` to be in line with the class.

This way the key values can be directly applied as class names.

**Review by dbauszus-glx — APPROVED** [review]

**Pull request merged**
