### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by simon-leech**
1. Been through the XYZ Framework and converted any english text strings into dictionary entries so we can update the translations. 
2. Updated the admin panel to allow administrators to change the language. This works on a lookup object so we store en or de to the database, but the user will see English or German

### CODE REVIEW

**Review by RobAndrewHurst — APPROVED** [review]
Nice!

When do we plan to add other languages to these translations?

**Comment by simon-leech** [comment]
https://docs.google.com/spreadsheets/d/1Rqf0wR7Tm8-yxDTUjct2iDK5dpnasYXm_zkRNU3zeMw/edit#gid=0

@RobAndrewHurst  I've set up this language translation sheet and we can crowd-source the translations from within the company - will ask people to fill in today. 

Wonder if we merge this PR and then open another when the translations are ready?

**Comment by dbauszus-glx** [comment]
Let me add the German translation now.

**Review by dbauszus-glx — APPROVED** [review]
Looks good.

**Comment by simon-leech** [comment]
I've got all the translations now - so will convert this back to draft until i'm implemented it - then open it again for review :)

**Comment by simon-leech** [comment]
This is now ready for review again. 
All the language translations have been implemented and I've updated the html to provide the options for each language option.

**Review by RobAndrewHurst — APPROVED** [review]
Nice one! Looks all good!

**Comment by simon-leech** [comment]
Just committed the Thai translations so we now have 11 supported languages - 

1. English
2. German
3. Spanish
4. French
5. Italian
6. Turkish
7. Chinese
8. Chinese (Traditional)
9. Thai
10. Polish
11. Japanese 
🎉🎉

**Pull request merged**
