### PR TITLE
ui.elements.dropdown: search input list filter

### PR DESCRIPTION
**Pull request by cityremade**
Related: https://github.com/GEOLYTIX/xyz/issues/1228

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206524747200757

### CODE REVIEW

**Comment by cityremade** [comment]
to apply on field:
```json
"filter": {
     "type": "in",
     "searchbox": true
 }```

**Comment by cityremade** [comment]
Closes #10

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
The lookup seems to check whether the letter is contained not whether the result begins with the search term.

Screenshot from 2024-05-13 10-15-25

image

Especially for the postcodes I would expect hundreds of results to be shown in the dropdown list.

Filter are just one example but the filter functionality should be added to the mapp.ui.elements.dropdown method to be available for any ui method.

layers filter should only contain an absolute minimum of ui logic.

**Comment by cityremade** [comment]
@dbauszus-glx this is the logic of the search function which is a simple js-esque .includes(pattern). As we discussed before, we could make this available to a wider circle and ask what/how people would like to find matching results.

**Pull request closed without merging**
