### PR TITLE
Fixes for infoj entry and filter issues

### PR DESCRIPTION
**Pull request by simon-leech**
**Issue**
* A `infoj` entry of `type:integer` will not be formatted correctly, neither formatting nor rounding is applied. 
* This was due to a check in line 30 of `numeric.mjs` that was conditional on `entry.formatterParams.locale`. However, there was no default applied. 
* I also noticed that providing a `maximumFractionDigit` of >2 when using certain locales (e.g. `en-GB`) was not applied.
* The `numericFormatter.mjs` was not checking if the type was integer so it was not formatting the value in the filter in this case. 

**Fixes** 
* The default locale is set to `en-GB`, but can be overriden in the configuration of an `infoj` entry. 
* If a `maximumFractionDigit` of >2 is applied, then the `minimumFractionDigit` (if not provided in the configuration), is set to the same value, so that this is applied. 
* `numericFormatter.mjs` now checks if the type if integer and sets the default locale to `en-GB`.  

**How to Test** 
Please test the various configuration options - examples below but this may not be exhaustive.
* `type: integer` + `formatterParams.locale` + `filter: integer`
* `type: numeric` + `round: 3` + `filter: numeric`
* `type: integer` + `filter: integer` 
* `type: numeric` + `filter: numeric`
``` json 
 {
      "field": "X",
      "type": "integer",
      "prefix": "£",
      "inline": true,
      "formatterParams": {
        "locale": "ar-EG"
      },
      "filter": {
        "type": "integer"
      }
    },
    {
      "field": "Y",
      "type": "numeric",
      "round": 3,
      "prefix": "£",
      "inline": true,
      "skipNullValue": true,
      "filter": {
        "type": "numeric"
      }
    },
    {
      "field": "Z",
      "type": "numeric",
      "prefix": "£",
      "inline": true,
      "skipNullValue": true,
      "filter": {
        "type": "numeric"
      }
    },
    {
      "field": "A",
      "type": "integer",
      "prefix": "£",
      "inline": true,
      "skipNullValue": true,
      "filter": {
        "type": "integer"
      }
    },

```

### CODE REVIEW

**Comment by AlexanderGeere** [comment]
I noticed the prefixes and suffixes werent not applying so i corrected that.

Prefixes and suffixes shouldnt apply in the filter input, nor will rounding, precision or min/maximumFractionDigits.

Looks good to me otherwise.

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
This working well but the default should be no locale.

Then if the user object is present with a language the user language should be used as the locale for the number formatting.

**Review by dbauszus-glx — APPROVED** [review]
Works well with one small change.

If locale is set use this locale.

If locale is nullish use the user language as locale.

If locale is NULL, do not use a locale.

```js
  // Assign user language as locale if nullish but not null.
  if (entry.formatterParams.locale !== null) {
    entry.formatterParams.locale ??= mapp.user.language;
  }
```

**Comment by simon-leech** [comment]
Updated the config docs to highlight this change. All ready to merge! 

https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#integer-1

**Review by RobAndrewHurst — DISMISSED** [review]
Please add in the updated documentation into the modules.

**Pull request merged**
