### PR TITLE
Add New Icons

### PR DESCRIPTION
**Pull request by simon-leech**
Adding new icons to the XYZ Icons Folder. 
The purpose of these icons is to provide flexibility for the SVG used for the User Guide button - as currently the report icon is used which is potentially confusing as this normally opens up a custom view.

### CODE REVIEW

**Comment by RobAndrewHurst** [comment]
What's the purpose of these icons?

**Comment by simon-leech** [comment]
@RobAndrewHurst I have edited the initial comment with context

**Review by RobAndrewHurst — APPROVED** [review]
LGTM!

These icons will be useful

**Comment by dbauszus-glx** [comment]
Can you also add them to the icons css?

**Comment by simon-leech** [comment]
@dbauszus-glx just added them to the icons CSS folder

**Review by dbauszus-glx — APPROVED** [review]

**Review by RobAndrewHurst — APPROVED** [review]

**Pull request merged**
