### PR TITLE
Tabulator utility methods (zoomToLocation and select)

### PR DESCRIPTION
**Pull request by simon-leech**
I've had a go at creating the RowDblClick function for zoomToLocation: true flag.
At the moment it returns an error, zoomToLocation is not a valid table constructor.

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
We cannot add custom feature flags to the Tabulator table config.

The reason why Tabulator warns on custom config is that in the future this may be a viable option within the Tabulator library.

image

**Comment by dbauszus-glx** [comment]
A feature like this should be introduced as a plugin first before this goes into the core.

**Comment by dbauszus-glx** [comment]
I commented out the _this.table.zoomToLocation to call the rowDouble click event handler to assign a method. This should be done by a plugin which assigns a method to the tabulatorUtils to be called as rowDoubleClick event.

I also commented out 'selectable' to assign the click method to select.

I added the 'select' method to the tabulator utilities as an example for the zoomToLocation method which you can assign here with a plugin.

The events are defined on the root of the dataview. I added a lookup for tabulator util methods to the check on the events object entries.

**Comment by dbauszus-glx** [comment]
I commented the rowSelect method in the select utility method.

```js
    if (typeof _this.rowSelect === "function") {
      _this.rowSelect(e, row);
      return;
    }
```

a custom select method should either be directly assigned to the events config or as tabulator util through a plugin.

**Comment by dbauszus-glx** [comment]
Seeing these two methods being almost the same I added that params being sent to the util.

This allows to extend methods like so:

```js
"events": {
  "rowClick": "select",
  "rowDblClick": {
    "util": "select",
    "zoomToLocation": true
  }
},
```

**Review by dbauszus-glx — APPROVED** [review]

**Comment by dbauszus-glx** [comment]
The util key/value must be provided to find the util. The entry including the util key/value is provided as second params argument to the utility method identified by the util key.

Params will be provided as string only the events key/value is a string e.g. `rowClick: 'select'`

**Comment by RobAndrewHurst** [comment]
Ah I s

> @RobAndrewHurst The util key/value must be provided to find the util. The entry including the util key/value is provided as second params argument to the utility method identified by the util key.
> 
> Params will be provided as string only the events key/value is a string e.g. `rowClick: 'select'`

Ah I see!!

**Comment by RobAndrewHurst** [comment]
@dbauszus-glx Are you waiting for my review before merging?

**Comment by dbauszus-glx** [comment]
@RobAndrewHurst Yeah, says review still pending.

**Comment by dbauszus-glx** [comment]
@RobAndrewHurst any advise how to lint this PR?

**Comment by RobAndrewHurst** [comment]
@dbauszus-glx I will provide a step by step today for this!

**Comment by RobAndrewHurst** [comment]
@dbauszus-glx @simon-leech 

I have linted the module.

Does it make sense to also require the `"selectable"` property on the dataview if the events are present on the dataview anyways?

I know its not required to make the event trigger, but then it just could be an extra step we don't need.

image

**Comment by RobAndrewHurst** [comment]
> It's just for the highlight. Without the selectable in the table options the row would not highlight on hover.

Yeah understand that!

**Review by RobAndrewHurst — APPROVED** [review]
### Tabulator utility methods (zoomToLocation and Select) (13/12/22)

- Good creation of a function in the tabulatorUtils.mjs that can be extended to acomodate other possible functionality!

**Pull request merged**
