### PR TITLE
UI elements input formatter

### PR DESCRIPTION
**Pull request by cityremade**
~~This pr is work in progress which builds on https://github.com/GEOLYTIX/xyz/pull/1310 and must not be merged before.~~

Numeric input element now includes formatting for prettiefied numbers;
.numericFormatter() now moved from mapp.ui.elements to mapp.utils;
Review + refactor for mapp.utils.numericFormatter;
Removing dependency on entry;
Simplifying defaults;
**Numeric entries will now get "formatter": "toLocaleString" by default. In order to disable it set "formatter": false;**

### CODE REVIEW

**Comment by simon-leech** [comment]
@cityremade  A few issues here - 
1. On initial load of a filter the greater than and less than boxes on the sliders are empty. 
image

2. When I drag the sliders to move them - the numbers aren't formatted in localeString.
image

3. When I then clear the filter and open it up again - the greater than and less than values are both the same but they are formatted? 
image

**Review by simon-leech — DISMISSED** [review]
Comments above

**Comment by simon-leech** [comment]
@cityremade  Just did another quick test - the numbers are now showing in the slider on initial load 😄
However ,they aren't formatted. The formatting is only applied when you close the filter and re-open it

**Comment by cityremade** [comment]
Here are some examples I've been testing with:

```{
                    "title": "numeric field",
                    "field": "numeric_field",
                    "filter": {
                      "type": "numeric"
                    },
                    "type": "numeric",
                    "edit":
                    {
                        "min": 0,
                        "max": 100,
                        "placeholder": "Number between 0 and 100"
                    }
                },
                {
                    "title": "numeric field non-edit",
                    "field": "_numeric_field",
                    "fieldfx": "numeric_field",
                    "type": "numeric",
                    "inline": true
                },
                {
                    "title": "integer field",
                    "field": "integer_field",
                    "type": "integer",
                    "edit": true,
                    "formatter": false,
                    "filter": {
                      "type": "integer"
                    }
                },
                {
                    "title": "range numeric",
                    "field": "range_numeric",
                    "type": "numeric",
                    "edit":
                    {
                        "range": true
                    }
                },
                {
                    "title": "input formatter",
                    "field": "input_formatter",
                    "type": "numeric",
                    "edit": true
                }```

**Comment by simon-leech** [comment]
@cityremade  There's a console.log in `slider_ab.mjs` that needs to be removed. 
And the values for me are still not formatted in the slider on initial load. This was my config I tested on. 

``` json
 {
      "title": "TITLE",
      "field": "field",
      "type": "integer",
      "filter": {
        "type": "integer"
      },
      "inline": true,
      "skipNullValue": true
    },
```

**Review by simon-leech — CHANGES_REQUESTED** [review]
@cityremade There's a console.log in slider_ab.mjs that needs to be removed.
And the values for me are still not formatted in the slider on initial load. This was my config I tested on.

 {
      "title": "TITLE",
      "field": "field",
      "type": "integer",
      "filter": {
        "type": "integer"
      },
      "inline": true,
      "skipNullValue": true
    },

**Review by RobAndrewHurst — CHANGES_REQUESTED** [review]
image

@cityremade The documentation is incorrect! Please review and let me know once this is ready for review.

**Comment by RobAndrewHurst** [comment]
Putting back into draft.

**Review by RobAndrewHurst — APPROVED** [review]

**Pull request merged**
