### PR TITLE
Geometry - Configurable Labels

### PR DESCRIPTION
**Pull request by simon-leech**
# Pull Request Template

## Description

1. When populating a geometry field using an API, we need to then run `update()` so that any `dependents` are also updated. 
2. Added `entry.edit.modify_label` and `entry.edit.delete_label` that can be configured. 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)

## How have you tested this? 
Tested locally.

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ Updated Existing Tests
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
The update command was taken out on purpose.

An API geometry can be stored within a plugin.

An API geometry may not be stored in the location at rest.

Turning on a catchment geometry without a field for display only will crash the process with the change in this PR.

```js
          {
            "label": "HERE Catchment",
            "type": "isoline_here",
            "params": {
              "apiKey": "***"
            }
          },
```

What should the expected behaviour be for ongoing edits?

I have a change in a text area. Displaying the geometry with a field will now update all val change entries and finish the edit mode.

image

**Comment by simon-leech** [comment]
@dbauszus-glx  Yeah i didn't think this was the best way to handle it. 

My use case is a third-party API call to a drivetime that then updates a separate field. The drivetime is not shown on the map (it has no style). When the drivetime call it finished the fields should be updated as it is a dependent of the geometry drivetime field.

**Comment by dbauszus-glx** [comment]
@simon-leech This will have to be done with the blocking capability. The geometry field entry will be ahead of the dependent field entry. 

The geometry entry has the blocking and display flag. If the entry has no value it will be generated. The location view is disabled with the blocking flag. After the geometry has been created and stored the location view will re-render. Dependent fields should be synced.

**Comment by dbauszus-glx** [comment]
@simon-leech What you are trying to do must be controlled in the plugin. 

The syncFields should be added to the finally condition of the call which requests the geometry. Whether a geometry is stored or not should not matter.

[Screencast from 25-06-24 09:54:25.webm](https://github.com/GEOLYTIX/xyz/assets/22201617/6b955ae5-a12b-4113-b5dd-854e8b67c330)


```js
    .finally(async () => {
      if (entry.dependents) {
        await entry.location.syncFields(entry.dependents)
      }
      entry.blocking && entry.location.view.dispatchEvent(new Event('render'))
    })
```

**Review by dbauszus-glx — APPROVED** [review]
Labels are working as expected.

image

```js
            "edit": {
              "delete_label": "Del",
              "modify_label": "Mod"
            },
```

**Pull request merged**
