### PR TITLE
Gazetteer using searchbox element;

### PR DESCRIPTION
**Pull request by cityremade**
Gazetteer definition now includes searchbox element. 
This fixes a conflict between behaviour of search result select and select from a dropdown element.

### CODE REVIEW

**Comment by RobAndrewHurst** [comment]
Also documented the ui/gazetteer module

**Review by simon-leech — COMMENTED** [review]
I don't know if this should be in the same PR or not - but there appears to be no hover CSS for list elements - which I think it quite unclear for the user. 
Should we change this in this PR or open a different one for it?

**Comment by RobAndrewHurst** [comment]
Oh I see what you mean

**Review by dbauszus-glx — APPROVED** [review]
Working well.

I added the CSS for webkit-search-cancel-button

**Review by simon-leech — APPROVED** [review]
All good with me and glad the CSS is resolved too :)

**Pull request merged**
