### PR TITLE
Only update dataview with activateUpdate or no data.

### PR DESCRIPTION
**Pull request by dbauszus-glx**
By default the dataview update method is triggered from the tab activate method.

With the `keepDataOnActivate` flag the update method will be shortcircuited in the tabview tab.activate() method.

The dataview can persist with this flag.

### CODE REVIEW

**Review by AlexanderGeere — COMMENTED** [review]
This flag should maybe be the default? `entry.keepDataonActivate ?? true`

**Comment by dbauszus-glx** [comment]
@AlexanderGeere The flag would be different ie. `updateOnActivate`. This would be more elegant but the problem is that the current behaviour will be changed. Should be discussed which way is preferred.

**Comment by simon-leech** [comment]
This is working well for me. 

I also think it should be the default to apply this so data is retained on activate of a tabview - and only if specified update the data every time the activate method is called.

**Comment by dbauszus-glx** [comment]
I reversed the logic to use the `activateUpdate` to update on activate if the entry data is not falsy.

**Review by simon-leech — APPROVED** [review]

**Review by RobAndrewHurst — APPROVED** [review]
I am happy with this change. I don't have time as of yet to write a test for the Tabview. 

We need to get to that at some stage. :( 

Or maybe someone can get to this while I am on leave?

**Pull request merged**
