### PR TITLE
added possible cause and fix message to common exception

### PR DESCRIPTION
**Pull request by eo-uk**
Added a try-catch block to explain the possible cause of the error and suggest a possible fix. This is a common error on filters due to v3 - v4 differences.

### CODE REVIEW

**Review by RobAndrewHurst — CHANGES_REQUESTED** [review]
Can you also include the field name in the error, so we know exactly what it relates to?

**Comment by eo-uk** [comment]
> Can you also include the field name in the error, so we know exactly what it relates to?

The actual error thrown after the message has that info. Eg: "Cannot create property 'field' on string 'numeric'"

**Comment by RobAndrewHurst** [comment]
> > Can you also include the field name in the error, so we know exactly what it relates to?
> 
> The actual error thrown after the message has that info. Eg: "Cannot create property 'field' on string 'numeric'"

Ah yes! Sorry, didn't see the `throw`!

**Review by RobAndrewHurst — APPROVED** [review]
Looks all good to me!

**Review by simon-leech — CHANGES_REQUESTED** [review]
This looks good to me. 

However, please could we also check that the filter object contains a type too, and if not provide a message for this?

I noticed that if you provide "filter":{} (without "type":"like" for instance) no error is raised but no filter is created either.

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
How is that line failing?

```
entry.filter.field = entry.filter.field || entry.field;
```

Can provide an example of the error thrown with the call stack.

**Comment by eo-uk** [comment]
> How is that line failing?
> 
> ```
> entry.filter.field = entry.filter.field || entry.field;
> ```
> 
> Can provide an example of the error thrown with the call stack.

image

**Comment by dbauszus-glx** [comment]
Instead of trying to assign a property to a string it should be checked whether entry.filter is an object.

**Comment by eo-uk** [comment]
> Instead of trying to assign a property to a string it should be checked whether entry.filter is an object.

Was about to do that, LBYL works well here. Will edit it soon. However, I think try-catch can be applied to a broader range of errors without spending too much time on them and is better than leaving a cryptic error alone.

**Review by simon-leech — APPROVED** [review]
This looks good to me - thanks for adding the check if type is provided too :)

**Comment by dbauszus-glx** [comment]
Would it be possible to create the object with the type if the check fails?

**Review by dbauszus-glx — APPROVED** [review]

**Pull request merged**
