### PR TITLE
nodemailer config from TRANSPORT environment variable

### PR DESCRIPTION
**Pull request by dbauszus-glx**
The transport variable must be split for the user, pass, host config for the nodemailer.

```
"TRANSPORT": "smtps:user:pass@host"
```

### CODE REVIEW

**Comment by RobAndrewHurst** [comment]
Shouldn't we not maybe just rule out the 'TRANSPORT' key?

**Comment by simon-leech** [comment]
I agree with @RobAndrewHurst , it makes the most sense to me to just have one option enabled which is the 3 keys required. Could we just add a warning if an instance contains the TRANSPORT key?

**Comment by dbauszus-glx** [comment]
@RobAndrewHurst @simon-leech Either will work for me.

**Review by simon-leech — APPROVED** [review]
This looks good to me - happier for it to be 3 keys and warnings on incorrect / missing!

**Review by RobAndrewHurst — APPROVED** [review]

**Pull request merged**
