### PR TITLE
get location from feature

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
# get location from feature

We have added in the ability to add features directly from a file or response onto a layer and provid a location from the `getInfoj` method in the `location/get.mjs` module.
A flag `featureLocation` has been introduced to the layer indicating that the layer will have featureLocations on it.

In the location/get.mjs module a new function `getFeatureResponse` has been introduced to help with returing a response from a getTemplate request or returned feature from the layer itself. The function will return the feature that matches the property id.

After we get the location we also remove all 'edit' flags on the infoj if it's a locationFeature as we don't want to be able to edit these.
I updated the `vector.test.mjs` to showcase this.

The `ui/layers/listview.mjs` has also been reviewed and updated.
The method no longer takes the entire `mapview`, but just the layers defined on the `mapview`. This changes allow us to append to the layer list instead of adding in every layer already defined on the `mapview`.

### CODE REVIEW

**Comment by RobAndrewHurst** [comment]
> WIP...

But pretty much done. Just need to do a write up in the PR, and Issue.

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
the layers listview method wants a proper re-review

params and properties were all over the place.

there was nested functions which should be assigned to the group/listview object.

the pattern for the listview module/method should be that of a decorator.

requires and dictionary entries must be reviewed.

**Comment by RobAndrewHurst** [comment]
I have moved the edit flag removal to the layer.decorate module.

This is ready for review.

**Review by cityremade — COMMENTED** [review]
Can this be used in a custom view where location is usually first retrieved to provide all information? Could it be a shorthand to draw feature on a map without the parent layer?

**Review by dbauszus-glx — APPROVED** [review]
Excellent works well for me with this little test workspace.

```json
{
  "locale": {
    "extent": {
      "north": 72,
      "east": 43,
      "south": 32,
      "west": -16,
      "mask": true
    },
    "minZoom": 3,
    "maxZoom": 15,
    "layers": {
      "OSM": {
        "display": true,
        "format": "tiles",
        "URI": "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        "style": {
          "contextFilter": "grayscale(100%)"
        },
        "attribution": {
          "© OpenStreetMap": "http://www.openstreetmap.org/copyright"
        }
      },
      "featurelayer": {
        "format": "geojson",
        "srid": "4326",
        "qID": "id",
        "featureLocation": true,
        "infoj": [
          {
            "type": "pin",
            "field": "pin"
          },
          {
            "title": "id",
            "field": "id"
          },
          {
            "title": "name",
            "field": "name"
          }
        ],
        "features": [
          {
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    -0.225,
                    51.48,
                    0
                  ],
                  [
                    -0.225,
                    51.52,
                    0
                  ],
                  [
                    -0.1,
                    51.52,
                    0
                  ],
                  [
                    -0.1,
                    51.48,
                    0
                  ],
                  [
                    -0.225,
                    51.48,
                    0
                  ]
                ]
              ]
            },
            "properties": {
              "id": 1,
              "name": "Greater London",
              "description": "A polygon covering central London",
              "pin": [
                -0.1625,
                51.5
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "Point",
              "coordinates": [
                -2.2426,
                53.4808,
                0
              ]
            },
            "properties": {
              "id": 2,
              "name": "Manchester City Centre",
              "description": "Point marking Manchester city centre",
              "pin": [
                -2.2426,
                53.4808
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    -3.203,
                    55.948,
                    0
                  ],
                  [
                    -3.203,
                    55.95,
                    0
                  ],
                  [
                    -3.199,
                    55.95,
                    0
                  ],
                  [
                    -3.199,
                    55.948,
                    0
                  ],
                  [
                    -3.203,
                    55.948,
                    0
                  ]
                ]
              ]
            },
            "properties": {
              "id": 3,
              "name": "Edinburgh Castle Area",
              "description": "Area around Edinburgh Castle",
              "pin": [
                -3.201,
                55.949
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "LineString",
              "coordinates": [
                [
                  -3.165,
                  51.462,
                  0
                ],
                [
                  -3.163,
                  51.463,
                  0
                ],
                [
                  -3.16,
                  51.464,
                  0
                ],
                [
                  -3.158,
                  51.4645,
                  0
                ]
              ]
            },
            "properties": {
              "id": 4,
              "name": "Cardiff Bay Walk",
              "description": "Walking path along Cardiff Bay",
              "pin": [
                -3.16,
                51.464
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    -5.92,
                    54.608,
                    0
                  ],
                  [
                    -5.92,
                    54.618,
                    0
                  ],
                  [
                    -5.91,
                    54.618,
                    0
                  ],
                  [
                    -5.91,
                    54.608,
                    0
                  ],
                  [
                    -5.92,
                    54.608,
                    0
                  ]
                ]
              ]
            },
            "properties": {
              "id": 5,
              "name": "Belfast Harbour",
              "description": "Area covering Belfast Harbour",
              "pin": [
                -5.915,
                54.613
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "LineString",
              "coordinates": [
                [
                  -3.006,
                  53.405,
                  0
                ],
                [
                  -3.004,
                  53.406,
                  0
                ],
                [
                  -3.002,
                  53.407,
                  0
                ],
                [
                  -3.0,
                  53.408,
                  0
                ]
              ]
            },
            "properties": {
              "id": 6,
              "name": "Liverpool Docks",
              "description": "Path along Liverpool's famous docks",
              "pin": [
                -3.002,
                53.407
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    -4.27,
                    55.858,
                    0
                  ],
                  [
                    -4.27,
                    55.863,
                    0
                  ],
                  [
                    -4.26,
                    55.863,
                    0
                  ],
                  [
                    -4.26,
                    55.858,
                    0
                  ],
                  [
                    -4.27,
                    55.858,
                    0
                  ]
                ]
              ]
            },
            "properties": {
              "id": 7,
              "name": "Glasgow City Center",
              "description": "Central area of Glasgow",
              "pin": [
                -4.265,
                55.8605
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "Point",
              "coordinates": [
                -1.2544,
                51.7548,
                0
              ]
            },
            "properties": {
              "id": 8,
              "name": "Oxford University",
              "description": "Central point of Oxford University",
              "pin": [
                -1.2544,
                51.7548
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "LineString",
              "coordinates": [
                [
                  -0.15,
                  50.82,
                  0
                ],
                [
                  -0.145,
                  50.8205,
                  0
                ],
                [
                  -0.14,
                  50.821,
                  0
                ],
                [
                  -0.135,
                  50.8215,
                  0
                ]
              ]
            },
            "properties": {
              "id": 9,
              "name": "Brighton Beach",
              "description": "Brighton Beach shoreline",
              "pin": [
                -0.14,
                50.821
              ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    0.115,
                    52.205,
                    0
                  ],
                  [
                    0.115,
                    52.21,
                    0
                  ],
                  [
                    0.12,
                    52.21,
                    0
                  ],
                  [
                    0.12,
                    52.205,
                    0
                  ],
                  [
                    0.115,
                    52.205,
                    0
                  ]
                ]
              ]
            },
            "properties": {
              "id": 10,
              "name": "Cambridge City Center",
              "description": "Historic center of Cambridge",
              "pin": [
                0.1175,
                52.2075
              ]
            }
          }
        ]
      }
    }
  }
}
```

**Comment by RobAndrewHurst** [comment]
> Can this be used in a custom view where location is usually first retrieved to provide all information? Could it be a shorthand to draw feature on a map without the parent layer?

This is more for reading geoJSON or wkt features and adding them to a layer.

I might be misunderstanding the use-case but see the [vector.test.mjs](https://github.com/GEOLYTIX/xyz/blob/cbae10ddaa421dd449f453dfeb50e8853c4d3f61/tests/lib/layer/format/vector.test.mjs) module for reference of what I am doing with the features

**Review by cityremade — APPROVED** [review]
Often maps in reports show surrounding area for the location and the location source layer is not needed, I would often apply filter by id in order to prevent showing the entire layer. I wouldn't need to pull the whole layer to show just one location.

**Review by AlexanderGeere — APPROVED** [review]
Nice One! Listview also working well.

**Pull request merged**
