### PR TITLE
Do not logout on failure to retrieve locales or locale

### PR DESCRIPTION
**Pull request by dbauszus-glx**
This causes issues with alternative login method, e.g. SAML.

An error to retrieve the locale e.g. from the server should not result in a log out.

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
Show a dialog instead of an alert.

**Review by simon-leech — APPROVED** [review]

**Review by RobAndrewHurst — APPROVED** [review]

**Review by RobAndrewHurst — COMMENTED** [review]
image

Are we happy with this?

**Comment by simon-leech** [comment]
@RobAndrewHurst  Looks good to me!

**Review by RobAndrewHurst — CHANGES_REQUESTED** [review]
image

Are we happy with this?

**Pull request merged**
