### PR TITLE
Fix feature properties

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
## Description

The properties are now spread into the OL element and we need to correct the feature properties references. 

## GitHub Issue

#1610 

## Type of Change
- ✅ Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
I have done a review of all OpenLayers feature getProperties() use cases.

https://github.com/GEOLYTIX/xyz/pull/1612/commits/afe5a35733023bb538608e538ec33607aa0b4194

These should always be stored as const featureProperties with the OL feature as F.

Please double check the cluster label assignment.

This is now working for me but was bugged.

image

**Review by dbauszus-glx — APPROVED** [review]
Working for me now.

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
The latest change of removing the +2 in the WKT featureFormats shift breaks the format.

**Comment by RobAndrewHurst** [comment]
> @RobAndrewHurst I don't understand the shift change.
> 
> I have two fields retailer, and store.
> 
> image
> 
> This means they are indexed 2 and 3. With 0 being the id and 1 being the geometry.
> 
> image
> 
> Removing the +2 in shift breaks WKT featureFormats method for me.
> 
> image

Yeah we noticed that now! We have come up with a fix!

Will document the fix now!

**Review by dbauszus-glx — APPROVED** [review]
Looking much cleaner now.

**Review by AlexanderGeere — APPROVED** [review]
Nice one!

**Review by simon-leech — APPROVED** [review]
Happy with this - tested on a range of layer formats

**Pull request merged**
