### PR TITLE
locale.locations: records, style, and pinStyle for locations listview

### PR DESCRIPTION
**Pull request by AlexanderGeere**
## Description

Adds the ability to apply a scale to the size of the pin of a location. The scale either be set in the locale using `pin_scale`, on the pin type or within in the listview_records:

locale.locations.pinStyle:
Screenshot 2024-09-03 120546

locale.locations.records or locale.listview_records:
Screenshot 2024-09-03 120704

entry type pin:
Screenshot 2024-08-27 152014

## GitHub Issue
[1423](https://github.com/GEOLYTIX/xyz/issues/1423)

## Type of Change
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Documentation

## How have you tested this? 
Tested using `bugs-testing/ui_elements/workspace.json`

## Testing Checklist 
- ✅ Existing Tests still pass
- ✅ Ran locally on my machine

## Code Quality Checklist
- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by simon-leech — COMMENTED** [review]
I'm happy with this - tested using this configuration and working as expected. 

``` json
 "locale": {
    "name": "TEST",
    "pin_scale": 1,
    "listview_records": [
      {
        "symbol": "A",
        "colour": "#2E6F9E",
        "scale": 10
      },
      {
        "symbol": "B",
        "colour": "#2E6F9E"
      },
      {
        "symbol": "C",
        "colour": "#2E6F9E"
      }
    ]
}
```
I like the introduction of a single `locale.pin_scale` to override them all, will be very useful instead of manually copy-pasting `listview_records` to achieve the same thing! 

image

**Review by simon-leech — APPROVED** [review]

**Comment by simon-leech** [comment]
Still to do before merging - write a test to test that this is working properly in all three use cases, will look at this today

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
There is still quite a bit to be done here...

Please have a look at my commit. https://github.com/GEOLYTIX/xyz/pull/1438/commits/5560f597ec36ce5d15eff0395e2968b9a17a2855

We do not want to overpopulate the locale, or any config object with ambiguous properties. The pin_scale can easily become pinscale or pinScale, then record_scale, and ultimately meaningless.

It's much easier to store properties of an object as properties of an object.

Eg. locations of a locale become locale.locations{}

pinStyle of locations become locations.pinStyle{}

records for locations become locations.records[]

This way everything is neatly nested in the locale.locations and we don't require excessive variables declared at sometime before methods nested in methods.

The scale property itself is too loose. The moment a scale property is introduced will lead to a colour property to be introduced in the future. Then a property for the type of icon. And perhaps an anchor. It is much easier to use the implicit nesting and defined a style as a style object. eg. pinStyle to encompass all the pin [icon] style config.

The gazCheck method has been unnested from the listview method. This method still needs to be documented proper.

I use the locale typedef for the gazCheck(locale) method. This typedef doesn't exist yet. I created an issue in this regard. #1442 

I unnested the setRecord method from the proxy. This method also wants to be documented proper.

The listview method documentation does need to be reviewed. The current description blurb doesn't explain at all what the method does. The listview docs should reference the inner method for setRecords.

```
The listview method appends a list of the selected locations to the provided target.

Creates the pins on each location using the styling supplied in locales.listview_records or defined on the entry type pin.
```

I'd recommend to do this last.

If a module is touched then all aspects of a module or at the very least all aspects of a method need to be reviewed.

In the case of the listview method we need to review and test the location.style and override as well as the pinStyle.

This will fail when I defined a custom locale.locations.records[] without a colour in the record.

```js
    location.style = {
      strokeColor: record.colour,
      fillColor: record.colour,
      fillOpacity: 0.1
    };
```

I have not reviewed the pin entry method yet as there is so much left to do in the listview module.

**Review by dbauszus-glx — APPROVED** [review]
The location style should be applied to geometries.

image

**Review by dbauszus-glx — DISMISSED** [review]
The location style / colour should be applied as default style to geometries if available.

**Comment by AlexanderGeere** [comment]
@dbauszus-glx The location style should now apply to geometries.

**Review by simon-leech — APPROVED** [review]
Lovely stuff - working for me :)

**Review by dbauszus-glx — APPROVED** [review]

**Comment by dbauszus-glx** [comment]
I removed the `location.Style` from the setter since this wasn't used.

I introduced `locale.locations.style{}` to define the default style into which the record will be spread.

`utils.style` should return null instead of undefined for null styles.

Entry style should be set to null for no styling instead of empty object.

The entry zIndex should be 1 more than the location.layer.zIndex.

https://github.com/GEOLYTIX/xyz/pull/1438/commits/d113938e03bd198654c7d90fa7de6432b8cc6736

**Pull request merged**
