### PR TITLE
added icon button element

### PR DESCRIPTION
**Pull request by eo-uk**
Added a button element with icon:

```
mapp.ui.elements.iconButton({
    data_id: "button-id",
    label: "Button Label",
    onclick: () => {console.log("foo")},
    iconURL: "<some_icon_url>",
    class: "<custom_classes>",
    style: "<custom_style>;",
    styleIcon: "<custom_icon_style>"
  })
 ```
  
image

### CODE REVIEW

**Comment by eo-uk** [comment]
I can move the css to core

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
style should be just params.style.

The default style should be added to _button.scss

**Review by RobAndrewHurst — APPROVED** [review]
Nice!

**Comment by RobAndrewHurst** [comment]
> style should be just params.style.
> 
> The default style should be added to _button.scss

@eo-uk Has done this in the proceeding commits!

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
Can you add the active class to the button. In order to toggle whether the button is styled as active in the callback method.

I would rename the method to buttonIcon or button_icon.

If there are multiple button methods we would like them to be consistent. Like slider, slider_ab, dropdown, dropdown_multi.

The type, e.g. button, slider, dropdown, etc. should be first followed by a modifier if needed.

The outside element should be type button not div to provide semantic html.

**Comment by eo-uk** [comment]
Outside element is already a button. Pushed the other requested changes.

**Review by dbauszus-glx — APPROVED** [review]

**Pull request merged**
