### PR TITLE
Codi 🐶 

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
## Welcome Codi! 🐶
I have replaced Jest with the lightweight test framework [Codi](https://www.npmjs.com/package/codi-test-framework).

Codi is a lightweight JavaScript test framework that allows you to write and run tests for your JavaScript code. It provides a simple and intuitive API for defining test suites and test cases, making it easy to ensure the correctness of your code. ✨

1. You can refer to the README.md on the Codi package for the different assertions built into Codi.

2. I have also included a new Roles test which will need to be updated in #1185.

To run the tests locally you will just need to execute `npm test` which will run codi against the tests directory.

### CODE REVIEW

**Comment by RobAndrewHurst** [comment]
image

Codi working in actions

**Comment by RobAndrewHurst** [comment]
image

Works with failing tests.

**Review by simon-leech — CHANGES_REQUESTED** [review]
@RobAndrewHurst  Think this is a Windows issue with Codi but can you  take a look? 
image

**Review by simon-leech — APPROVED** [review]
@RobAndrewHurst  Thanks all running for me now!

**Review by dbauszus-glx — APPROVED** [review]
This works for me. I added merge.test.mjs which passed.

I only use assertDeepEqual. I think we can get rid of assertEqual in favour of always using the deepEqual logic.

image

**Pull request merged**
