### PR TITLE
Create proxy module for mapp.dictionary to check for mapp.language and lookup key

### PR DESCRIPTION
**Pull request by dbauszus-glx**
The dictionary proxy has been moved from the mapp module script to a module in the dictionaries directory.

The getter proxy will now check whether the language exists in the dictionaries, and whether the key exists in either the language or default english dictionary.

The key will be returned if no lookup is available.

The dictionary proxy must not crash.

### CODE REVIEW

**Review by simon-leech — CHANGES_REQUESTED** [review]
I tested by swapping my language to Chinese. I correctly get the Chinese translation where available and otherwise get the default of English. 

I tested by swapping my language to 'TEST' which is obviously bogus. I get no crash and just see English. 

However I see 43 console warnings , I assume this is one for every key that's not available? Do we want to just have a single warning instead of filling the console with the same warning repeatedly? 
image

**Comment by dbauszus-glx** [comment]
@simon-leech We can set the mapp.language to english in the default view if the issue is the number of warnings. But we shouldn't mess with debouncing warnings or altering the user/mapp language inside the dictionary proxy getter.

**Review by simon-leech — APPROVED** [review]

**Comment by dbauszus-glx** [comment]
I added a check for the user language to the default view to reduce the number of warnings.

**Review by simon-leech — APPROVED** [review]

**Comment by simon-leech** [comment]
Still to do before merging - write a test to test that an unknown language warns and sets to English. The other language tests are passing so just need to do this, will have a look today

**Comment by simon-leech** [comment]
I just pushed a test for checking that a 'language' of "TEST" is correctly updated to "en" and does not crash - this is passing so the process is working.

Please can someone review this?

**Review by RobAndrewHurst — APPROVED** [review]
Happy with this!

**Pull request merged**
