### PR TITLE
Dialog headerDrag

### PR DESCRIPTION
**Pull request by simon-leech**
## Description

Added the `headerDrag` flag that when set will mean dialogs are only draggable from the header. The body of the dialog is then accessible for mouse clicks / interactions by the user.

Fixed bug with error about `resizeObserver`. 

## GitHub Issue

https://github.com/GEOLYTIX/xyz/issues/1356

## Type of Change

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)

## How have you tested this? 
Tested locally.

## Testing Checklist 

- ✅ Existing Tests still pass
- ✅ Ran locally on my machine

## Code Quality Checklist

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by AlexanderGeere — DISMISSED** [review]
Works well. The cursor should change to `grab` when you hover the header.

**Comment by simon-leech** [comment]
@AlexanderGeere  I just pushed a commit to add CSS for the `headerDrag` so on hover it chagnes to a `grab` `cursor`. 

Also updated the docs to include the `headerDrag` flag. 

Ready for re-review

**Review by RobAndrewHurst — APPROVED** [review]
Nice one! Works well! 

Thanks for updating the docs

**Comment by dbauszus-glx** [comment]
How do I add a modal dialog to the document.body?

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
This feels odd.

A target element is required but not used for modal dialog.

image

**Comment by dbauszus-glx** [comment]
The dialog should be meaningful and legible with just content.

```js
    mapp.ui.elements.dialog({
      content: mapp.dictionary.no_layers
    });
```

image

**Comment by dbauszus-glx** [comment]
I committed the check on target for modal and the test in the default view to this PR.

**Comment by dbauszus-glx** [comment]
The jsdoc block needs to be reviewed. Only one param with property is passed to the dialog element function.

**Comment by dbauszus-glx** [comment]
By definition of a modal dialog only one can exists at the same time.

An existing modal dialog should be closed when a modal dialog is added.

```js
  // Close existing modal.
  document.querySelector('dialog.modal')?.close()
```

**Comment by dbauszus-glx** [comment]
I moved the modal close button to the corner in css and removed the now unused .modal-map from style sheets.

The close button can be defined inside the dialog css. This doesn't have to be defined twice.

The close should always be conditional. We want to be able to create a modal which cannot be closed by user.

The closeBtn is assigned to the dialog object on nullish condition allowing to provide a custom closeBtn with the dialog object argument.

The dialog script is easier to read with one check on modal and else for non modal.

https://github.com/GEOLYTIX/xyz/pull/1367/commits/9e0203564e08a444ab0eb3de44b377411a56f5c7

**Review by dbauszus-glx — APPROVED** [review]
this is now working as expected.

**Review by AlexanderGeere — APPROVED** [review]

**Pull request merged**
