### PR TITLE
Mobile View Fixes

### PR DESCRIPTION
**Pull request by simon-leech**
## Description

This addresses 3 issues on mobile:
1. clicking on an `li` element in the cluster popup did not trigger the event.  Swapped to `onpointerup` to handle both mobile and desktop selections. 
2. Added a mobile util which set the maxWidth in the default view and returns true if called on mobile. This means th
3. This means that both infoj and layer dataviews are hidden as the mobile util is called at their start 
4. Updated the css of the map-attribution to include user-select:none to prevent select of it when you pull up the tabs on a smaller screen.

Please test this on both desktop view and also on a mobile display!
## GitHub Issue

#1269 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ Updated Existing Tests
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by AlexanderGeere — APPROVED** [review]

**Review by dbauszus-glx — DISMISSED** [review]
I added a mobile util which set the maxWidth in the default view and returns true if called on mobile.

The dataview entry should just return on mobile.

The tabview should not be shown on mobile devices and should always have the `mobile-display-none` class.

```
entry?.tabview?.classList.contains('mobile-display-none')
```

Update queries should not be executed on mobile devices.

The public geodata instance has a dataview query which executtes despite the tabview not shown.

image

The attribution and logo should not be selectable.

**Comment by simon-leech** [comment]
I have added the same util to be called when creating dataviews in the layer panel. So layer dataviews are also hidden on mobile.
I have updated the css of the `map-attribution` to include `user-select:none` to prevent select of it when you pull up the tabs on a smaller screen.

This is ready for re-review

**Review by dbauszus-glx — APPROVED** [review]
The changes work for me but I also did some changes myself. This ust be reviewed by someone else too.

**Comment by RobAndrewHurst** [comment]
image


I am all happy with this!

I ran some tests on different devices on browser stack running the application locally!

**Review by RobAndrewHurst — APPROVED** [review]

**Pull request merged**
