### PR TITLE
Drawing elements for layer and geometry location entry (refactor)

### PR DESCRIPTION
**Pull request by dbauszus-glx**
`layer.draw{}` is the configuration for drawing on a layer. The layer decorator will warn if a `layer.edit{}` config is found and create a draw config from the edit config.

The layer decorator assigns a callback method to the draw config. The callback method receives an Openlayers feature as argument and post the feature geometry to the `location/new` endpoint. An ID must be returned from a serial field in the layer table. Default property values defined in the draw config will be assigned in the post body.

```js
  if (layer.edit) {
    console.warn('layer.edit has been superseeded with layer.draw to be in line with the OL drawing interaction.')
    layer.draw = Object.assign(layer.draw || {}, layer.edit)
  }

  if (layer.draw) {

    // Callback which creates and stores a location from a feature returned by the drawing interaction.
    layer.draw.callback = async feature => {
 
      if (!feature) return;
    
      const location = {
        layer,
        new: true
      }
    
      // Store location in database.
      // The id must be returned from a serial ID field.
      location.id = await mapp.utils.xhr({
        method: 'POST',
        url: `${layer.mapview.host}/api/location/new?` +
          mapp.utils.paramString({
            locale: layer.mapview.locale.key,
            layer: layer.key,
            table: layer.tableCurrent()
          }),
        body: JSON.stringify(Object.assign({
          [layer.geom]: feature.geometry
        },

        // Assign default properties.
        layer.draw?.defaults || {}))
      })
    
      layer.reload()
    
      // Get the newly created location.
      mapp.location.get(location)
    }
  }
```

The layer draw panel method iterates through all keys of the layer draw config and provides the layer as argument to a matching drawing element method. The array of elements returned from the drawing element methods are added to the layer draw panel which is added to the layer view.

```js
export default layer => {

  if (typeof layer.draw !== 'object') return;

  // Do not create the panel.
  if (layer.draw.hidden) return;
 
  const elements = Object.keys(layer.draw)
    .map(key => {

      // Return element from drawing method.
      return mapp.ui.elements.drawing[key] && mapp.ui.elements.drawing[key](layer)
    })
    .filter(node => !!node)

  // Short circuit panel creation without elements.
  if (!elements.length) return;

  const panel = mapp.ui.elements.drawer({
    data_id: `draw-drawer`,
    class: 'raised',
    header: mapp.utils.html`
      <h3>${mapp.dictionary.layer_add_new_location}</h3>
      <div class="mask-icon expander"></div>`,
    content: mapp.utils.html`
      ${elements}`,
  });

  return panel;
}
```

An `entry.draw` config must be set for geometry entries in order to draw a geometry. There is no fallback for draw configs defined as `entry.edit` for geometry entries. The reason being that geometry editing (modify interaction) and drawing are both possible on the same geometry entry. Drawing a geometry will overwrite the existing geometry value.

The geometry method will iterate over the keys defined in the draw config and add the drawing elements returned from the matching methods to the entry node in the location view. The entry passed as argument to the drawing element method is effectively the same as the layer which is passed from the layer draw panel.

A callback method is assigned to the entry draw config. The callback will update the geometry entry value with the geometry from the Openlayers feature returned from the drawing interaction.

```js
  if (typeof entry.draw === 'object') {

    entry.mapview = entry.location.layer.mapview

    entry.draw.callback = feature => {

      if (!feature) return;

      // Remove existing entry geometry layer.
      entry.location.layer.mapview.Map.removeLayer(entry.L)

      // Assign feature geometry as new value.
      entry.newValue = feature.geometry
      entry.location.update()
    }

    Object.keys(entry.draw).forEach(key => {
      if (mapp.ui.elements.drawing[key]) {
        list.push(mapp.ui.elements.drawing[key](entry))
      }
    })

  }
```

All drawing elements methods receive a layer object as the only argument. The element method first assigns the existing draw config to the defaults. The layer itself must be assigned to the config object which is passed as params argument to the mapview draw interaction. The layer/entry draw callback method which receives an Openlayer feature from the mapview draw interaction must be assigned to the draw type config object.

There is some script repetition in the onclick event handler of the button element. This is a conscious decision to make the script more legible. Methods can be added to the drawing element methods. The isoline methods will be removed from this module and provided as plugins which contain any supporting utils.

All DOM references must be contained in the drawing element method. e.g. toggling the class of a button element.

The button element which toggles the drawing interaction is assigned as btn to the config object. Every drawing element[group] must only have one button which calls the drawing interaction. This button will always be the btn element in the config. These buttons must all the same look and feel. Resulting from this there can be no two circle interactions in one element. The manual circle creation has been split from the circle from centre point creation as `circle_2pt`.

Any textual component must be defined in the `mapp.dictionaries`.

```js
function point(layer) {

  layer.draw.point = Object.assign
    layer,
    type: 'Point',
  }, typeof layer.draw.point === 'object' && layer.draw.point || {})
  
  layer.draw.point.btn = mapp.utils.html.node`
    <button
      class="flat wide bold primary-colour"
      onclick=${e=>{

        const btn = e.target

        if (btn.classList.contains('active')) {
          btn.classList.remove('active')
          layer.mapview.interactions.highlight()
          return;
        }
      
        btn.classList.add('active')
        
        layer.show()
      
        layer.draw.point.callback = feature => {
      
          layer.draw.callback(feature)
      
          if (btn.classList.contains('active')) {
            btn.classList.remove('active')
            layer.mapview.interactions.highlight()
          }
        }
      
        layer.mapview.interactions.draw(layer.draw.point)
        
      }}>
      ${mapp.dictionary.draw_point}`

  return layer.draw.point.btn
}
```

Configuration elements (e.g. Radius and Units for circle construction) are stored as `.panel` in the draw config. The panel is returned in a drawer as previous element sibling to the interaction button. Activating the interaction through the button will expand the panel. All panel configurations are live and can be changed before activating an interaction or while an interaction is current.

```js
  layer.draw.circle.panel = mapp.utils.html.node`
    <div class="panel flex-col">
      ${unitsDropDown}
      ${rangeSlider}`

  layer.draw.circle.btn = mapp.utils.html.node`
  <button
    class="flat wide bold primary-colour"
    onclick=${e=>{

      const btn = e.target

      if (btn.classList.contains('active')) {
        btn.classList.remove('active')
        layer.mapview.interactions.highlight()
        return;
      }

      // Expand the config drawer.
      btn.previousElementSibling.classList.add('expanded')
    
      btn.classList.add('active')
      
      layer.show()
    
      layer.draw.circle.callback = feature => {
    
        layer.draw.callback(feature)
    
        if (btn.classList.contains('active')) {
          btn.classList.remove('active')
          layer.mapview.interactions.highlight()
        }
      }
    
      layer.mapview.interactions.draw(layer.draw.circle)
      
    }}>
    ${mapp.dictionary.draw_circle}`

  // Return the config element in a drawer with the interaction toggle button as sibling.
  return mapp.utils.html.node`<div>
    ${mapp.ui.elements.drawer({
      header: mapp.utils.html`
        <h3>${mapp.dictionary.circle_config}</h3>
        <div class="mask-icon expander"></div>`,
      content: layer.draw.circle.panel
    })}
    ${layer.draw.circle.btn}`
```

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
The circle config elements do now work as intended.

`radiusMin` and `radiusMax` can be configured in the config object.

The conversion method can be assigned as well for custom unit conversions.

The conversion is done in the geometryFunction.

```js
  layer.draw.circle = Object.assign({
    layer,
    type: 'Point',
    units: 'meter',
    radius: 100,
    radiusMin: 1,
    radiusMax: 1000,

    // Methods to transform input radius.
    unitConversion: {
      meter: v => v,
      km: v => v * 1000,
      miles: v => v * 1609.34,
      meter2: v => Math.sqrt(v / Math.PI),
      km2: v => Math.sqrt(v * 1000000 / Math.PI),
    },
    geometryFunction: (coordinates) => {

      const polygonCircular = new ol.geom.Polygon.circular(
        ol.proj.toLonLat(coordinates),
        layer.draw.circle.unitConversion[layer.draw.circle.units](layer.draw.circle.radius),
        64
      );

      return polygonCircular.transform('EPSG:4326', 'EPSG:3857')
    }
  }, typeof layer.draw.circle === 'object' && layer.draw.circle || {})
  
  const unitsDropDown = mapp.utils.html.node`
    <div style="display: grid; grid-template-columns: 100px 1fr; align-items: center;">
      <div style="grid-column: 1;">Units</div>
      <div style="grid-column: 2;">
        ${mapp.ui.elements.dropdown({
          placeholder: layer.draw.circle.units,
          entries: [
            {
              title: 'Meter',
              option: 'meter',
            },
            {
              title: 'KM',
              option: 'km',
            },
            {
              title: 'Miles',
              option: 'miles',
            },
            {
              title: 'Meter²',
              option: 'meter2',
            },
            {
              title: 'KM²',
              option: 'km2',
            },
          ],
          callback: (e, entry) => {
            layer.draw.circle.units = entry.option;
          }
        })}`

  const rangeSlider = mapp.ui.elements.slider({
    label: 'Radius',
    min: layer.draw.circle.radiusMin,
    max: layer.draw.circle.radiusMax,
    val: layer.draw.circle.radius,
    callback: e => {
      layer.draw.circle.radius = parseFloat(e.target.value)
    }
  })
```

**Comment by dbauszus-glx** [comment]
I added a commit which provides the draw config as optional argument with the feature to the layer.draw.callback.

https://github.com/GEOLYTIX/xyz/pull/671/commits/e75648b34569682269a89061028f7d273ca91a4e

The defaults assigned to the params/config object will be assigned to the post body for new locations.

```js
      // Store location in database.
      // The id must be returned from a serial ID field.
      location.id = await mapp.utils.xhr({
        method: 'POST',
        url: `${layer.mapview.host}/api/location/new?` +
          mapp.utils.paramString({
            locale: layer.mapview.locale.key,
            layer: layer.key,
            table: layer.tableCurrent()
          }),
        body: JSON.stringify(Object.assign({
          [layer.geom]: feature.geometry
        },

        // Assign default properties.
        params?.defaults || {},
        layer.draw?.defaults || {}))
      })
```

**Comment by RobAndrewHurst** [comment]
@dbauszus-glx 

I found some issues when drawing on a location.

1. I couldn't get the line type to save on a location.
2. Also couldn't get any other drawing type (ie circle,  rectangle, polygon ) to render on the layer after saving it. The only one that worked for me was a point.

Bellow is one example of the rectangle not rendering after being saved!

https://user-images.githubusercontent.com/43169158/232740903-20d76543-e839-42f2-8f92-6a3263ec6604.mov

**Comment by RobAndrewHurst** [comment]
> @dbauszus-glx
> 
> I found some issues when drawing on a location.
> 
> 1. I couldn't get the line type to save on a location.
> 2. Also couldn't get any other drawing type (ie circle,  rectangle, polygon ) to render on the layer after saving it. The only one that worked for me was a point.
> 
> Bellow is one example of the rectangle not rendering after being saved!
> 
>  Screen.Recording.2023-04-18.at.11.51.49.mov

This issue that I pointed out now relates to a bug!

**Pull request merged**
