### PR TITLE
Remove legacy node-fetch and document mod/cloudfront ☁️

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
## Description

I have removed the `node-fetch` reference in the cloudfront.js mod.

I also added in documentation for the script.
## GitHub Issue

https://github.com/GEOLYTIX/xyz/issues/1641 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Documentation

## Code Quality Checklist

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have removed the `node-fetch` reference from the cloudfront.js module and added documentation for the script. Here are the changes I made:

1. Removed the `const nodeFetch = require('node-fetch')` line.
2. Replaced `nodeFetch` with the global `fetch` function.
3. Added JSDoc comments to describe the module and its main function.

These changes align with the request to remove the node-fetch reference and add documentation. The use of the global `fetch` function is compatible with Node.js versions 18 and above, which is specified in the package.json file.

I also created pull request: https://github.com/GEOLYTIX/xyz/pull/1646


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by dbauszus-glx** [comment]
I have updated the docs. There was some heavy nesting on the properties which were defined as params.

image


This is now cleaned up.

image

I also added the module requires to the module block.

image

**Comment by dbauszus-glx** [comment]
I still want to test this failing. I think the try...fetch is just there to throw an error if the key is undefined or fails to sign. I want to actually test this providing a false key and a false resource.

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
#1542 must be merged into this PR.

The provider module must return an Error rather than text failed to retrieve resource.

The cloudfront module must export null if the cloudfront key is not defined rather than throwing an Error which isn't caught.

The cloudfront module must return an Error and not just throw and Error with no return if the resource is not available or failed to resource.

The urlSigner should be a signer module to be imported by the provider module for internal use. signedUrl request should be rerouted to the cloudfront signer module.

**Review by dbauszus-glx — APPROVED** [review]
This is good to go. I create a seperate issue for the code structure and security concerns.

https://github.com/GEOLYTIX/xyz/issues/1651

**Pull request merged**
