### PR TITLE
Dataview review

### PR DESCRIPTION
**Pull request by dbauszus-glx**
Allow for chartjs dataviews to setData with data provided on object.

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
ui.utils.Chart has been refactored to load and construct the ChartJS dataview.

The loader has been moved from the Dataview module to the utils module.

`noDataMask` can be defined as a string.

`mask` can be defined as an HTMLElement.

**Comment by dbauszus-glx** [comment]
Tabulator constructor has been moved with library loaded.

Cognitive load has been reduced. setData works for data provided with entry.

noMask can be defined as string.

**Comment by RobAndrewHurst** [comment]
> ui.utils.Chart has been refactored to load and construct the ChartJS dataview.
> 
> The loader has been moved from the Dataview module to the utils module.
> 
> `noDataMask` can be defined as a string.
> 
> `mask` can be defined as an HTMLElement.

how does the mask property work? Is there an example of this?

**Comment by dbauszus-glx** [comment]
@RobAndrewHurst  No data mask example.

```js
{
 "display": true,
 "type": "dataview",
 "target": "location",
 "query": "nodata",
 "noDataMask": "¡No Bueno!",
 "chart": {}
},
```

With
```js
"templates": {
  "nodata": {
    "template": "select null;"
  }
},
```

**Comment by RobAndrewHurst** [comment]
> @RobAndrewHurst No data mask example.
> 
> ```js
> {
>  "display": true,
>  "type": "dataview",
>  "target": "location",
>  "query": "nodata",
>  "noDataMask": "¡No Bueno!",
>  "chart": {}
> },
> ```
> 
> With
> 
> ```js
> "templates": {
>   "nodata": {
>     "template": "select null;"
>   }
> },
> ```

I understand the `noMaskData` property. I am asking more specifically about the `mask` property mentioned in your comment above?

**Comment by dbauszus-glx** [comment]
@RobAndrewHurst You would need to define the mask property as an HTML element. Can only be done in a plugin like so:

```js
dataview.mask = mapp.utils.html.node`<div>Text`
```

**Review by RobAndrewHurst — APPROVED** [review]

**Review by simon-leech — APPROVED** [review]
This is all working for me - happy to merge!

**Pull request merged**
