### PR TITLE
Default view dialog fixes

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
## Description

The no_locales and no_layers dialogs on the default view were displaying as full modals which would prevent the user from accessing any other controls in the mapview. (admin or logout).

Fixes.
1. Gave the two dialogs a target, because if a dialog does not have a target it is a modal.
2. I removed the 'px' suffix because a user may want to set the position with other units other than 'px'.
3. Fixed the 'helpDialog' to use 'px' in the config.
## GitHub Issue
https://github.com/GEOLYTIX/xyz/issues/1421

## Type of Change
- ✅ Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
Defaults should not be in pixel. `em` or event percent are preferred.

**Comment by RobAndrewHurst** [comment]
> Defaults should not be in pixel. `em` or event percent are preferred.

Is this in reference to the helpDialog module?

**Comment by dbauszus-glx** [comment]
> > Defaults should not be in pixel. `em` or event percent are preferred.
> 
> Is this in reference to the helpDialog module?

Yes. It's this one.
image

**Comment by RobAndrewHurst** [comment]
@dbauszus-glx This has been fixed!

**Review by AlexanderGeere — APPROVED** [review]
Looks good!

**Review by dbauszus-glx — APPROVED** [review]

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
Should the dialog be on the mapview element or the document.body?

There should be a little bit of margin to the element as this looks somewhat squashed.

image

**Comment by RobAndrewHurst** [comment]
> Should the dialog be on the mapview element or the document.body?
> 
> There should be a little bit of margin to the element as this looks somewhat squashed.
> 
> image

image

I have no made it part of the body, and added in a z-index style on the dialogs to ensure they are on top of everything because a dialog element won't have that but a Modal will.

**Comment by RobAndrewHurst** [comment]
@dbauszus-glx Do we want the option to have a dialog that you cannot move? Or are we starting to call a spade something else?

**Comment by dbauszus-glx** [comment]
> @dbauszus-glx Do we want the option to have a dialog that you cannot move? Or are we starting to call a spade something else?

Don't think that's needed. A modal doesn't move and should be used in that case.

**Comment by RobAndrewHurst** [comment]
> > @dbauszus-glx Do we want the option to have a dialog that you cannot move? Or are we starting to call a spade something else?
> 
> Don't think that's needed. A modal doesn't move and should be used in that case.

This is ready for a re-review then.

**Review by AlexanderGeere — APPROVED** [review]
Dialog could probably open a little to the right, but otherwise looks good to me

**Review by dbauszus-glx — APPROVED** [review]
I have updated the margins and css to have the dialog at a max-width of 50%, left 25%, and slightly top: 40%.

The dialog is more prominent if slightly top, centre, and not full width.

image

**Comment by RobAndrewHurst** [comment]
I am happy with this!

**Pull request merged**
