### PR TITLE
Eslint changes

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
## Description

I have created an [eslint](https://eslint.org/docs/latest/) config that will help us to address multiple issues that we have been having with code quality.

The main rules that have been included currently are : 

- Use single quotes only.
- Use const if the variable is not reassigned.
- Have a max depth of 4.
- Ensure that complexity of a script does not go above 15.
- No nested ternary operations.

To run this you will need to install the npm packages and run `npx eslint .`

## Type of Change
- ✅ Testing

### CODE REVIEW

**Review by dbauszus-glx — DISMISSED** [review]
This works well for me with the ESLint extenion for VSCode. https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

image

The commands need to be added to the DEVELOPING.md

**Review by dbauszus-glx — APPROVED** [review]
This working well now.

The DEVELOPING notes are clear.

**Review by simon-leech — APPROVED** [review]
This is good for me now :)

**Review by AlexanderGeere — APPROVED** [review]
Working for me now. Nice!

**Review by cityremade — APPROVED** [review]

**Pull request merged**
