### PR TITLE
ACL No User Present and Verification bugs

### PR DESCRIPTION
**Pull request by RobAndrewHurst**
### ACL Bugs

This PR is solving two bugs 

1. Do not throw `auth_failed` error if there is no user in acl.
2. If the user verifies themselves and they are not resetting their password do not update the password. This check was removed in this [pr](https://github.com/GEOLYTIX/xyz/pull/1137)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206773921055416
  - https://app.asana.com/0/0/1206773491322403

### CODE REVIEW

**Comment by RobAndrewHurst** [comment]
I have updated the docs for the fromACL module in xyz.

I also included the github link in the navbar of the docs site!

**Review by dbauszus-glx — APPROVED** [review]
Well spotted to not throw error when the user isn't found.

**Comment by RobAndrewHurst** [comment]
@dbauszus-glx Will need you to re-review as I have also added back in a check on the verify module where we can reset a users password.

**Review by simon-leech — APPROVED** [review]
Tested this by - 
Adding a new user and setting password
Received email to verify
Received email that was approved
Can then login 

Reset password 
Received email to verify password reset
Can then login

**Comment by RobAndrewHurst** [comment]
There is still an issue here. Going back into draft

**Comment by dbauszus-glx** [comment]
This looks cleaner with a substitute params array.

```js
  let substitute_params = [user.email, req.params.language || user.language]

  user.password_reset && params.push(user.password_reset)

  // Update user account in ACL with the approval token and remove verification token.
  rows = await acl(`
    UPDATE acl_schema.acl_table SET
      failedattempts = 0,
      ${user.password_reset && `password = $3,` ||''}
      verified = true,
      verificationtoken = null,
      language = $2
    WHERE lower(email) = lower($1);`, substitute_params)
```

**Comment by RobAndrewHurst** [comment]
Nice that's exactly what I was discussing with @AlexanderGeere

**Review by AlexanderGeere — APPROVED** [review]
All looks good to me!

**Review by dbauszus-glx — APPROVED** [review]
Can login with user.

Delete user.

Can not login with the user.

Register user.

Can not login with user.

Verify User.

Can not login with user.

Approve User.

Can login with user.

Reset password.

Can login with existing password.

Verify password reset.

Can login with new password.

**Pull request merged**
