### PR TITLE
Check for feature.set method

### PR DESCRIPTION
**Pull request by dbauszus-glx**
Vector tile layer features do not have a set method.

### CODE REVIEW

**Review by simon-leech — APPROVED** [review]
Fixes the described bug - happy to merge!

**Review by simon-leech — CHANGES_REQUESTED** [review]
Similar error is seen on highlight in the highlight.mjs file. 
Line 291 
 // Unset cached style to allow for highlight style.
    mapview.interaction.current.F.set('Styles', null, true)

**Review by simon-leech — CHANGES_REQUESTED** [review]
@dbauszus-glx Thanks for that - this is now working for non-mvt layers. 
However, on mvt layers there is a new error. 
This originates from line 204 in highlight.mjs this code
    // Unset cached OL Styles object.
    feature?.F?.set('Styles', null, true).

The error occurs on higlight of an mvt layer - see image. 
image

**Comment by dbauszus-glx** [comment]
@simon-leech I moved the second feature set method into the block which checks whether the method is available.

**Review by simon-leech — APPROVED** [review]
This is looking good to me now - no further errors on either style or highlight on mvt / non-mvt layers. Happy to merge!

**Review by RobAndrewHurst — APPROVED** [review]

**Pull request merged**
