### PR TITLE
Update queryParams documentation

### PR DESCRIPTION
**Pull request by dbauszus-glx**
Updates the jsdoc for queryParams utility module.

### CODE REVIEW

**Review by AlexanderGeere — CHANGES_REQUESTED** [review]
The documentation would imply that `_this.layer` is optional but if you do not supply it the function crashes.

**Comment by dbauszus-glx** [comment]
@AlexanderGeere The layer object is optional. The layer is only required if a viewport, centre, z, or table are to be returned.

I have updated the property notes.

**Review by AlexanderGeere — APPROVED** [review]

**Comment by AlexanderGeere** [comment]
@dbauszus-glx  I added some test 👍

**Review by simon-leech — APPROVED** [review]
I fixed 2 spelling mistakes and one failing test - all good with me

**Review by RobAndrewHurst — APPROVED** [review]

**Pull request merged**
