### PR TITLE
Missing HelpDialog for Editing a Geometry Editing

### PR DESCRIPTION
**Pull request by simon-leech**
It was noticed that when you are editing an `infoj` `geometry` `entry` - you are not provided with a `helpDialog` , when you do get this for drawing. 

This PR simply adds a `helpDialog` for this. 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)

## Testing Checklist 

- ✅ Existing Tests still pass
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by RobAndrewHurst — APPROVED** [review]
Looks good to me!

**Comment by RobAndrewHurst** [comment]
Actually do we want the dialog to be optional?

**Comment by simon-leech** [comment]
> Actually do we want the dialog to be optional?

Isn't the current helpDialog on drawing interaction always shown, so I followed that pattern.
 
I don't think it should be optional as surely its helpful to see it for reference to the available options?

**Comment by RobAndrewHurst** [comment]
We might want to consider this for an issue, and another PR

**Comment by simon-leech** [comment]
> We might want to consider this for an issue, and another PR

Yeah good point on custom views. 

I think the problem is I think it should be default true, but you can turn it off if required - in case not wanted. 
But in general, I think its an important feature to show users 😅

Agreed maybe we want an issue with RFC

**Review by RobAndrewHurst — APPROVED** [review]

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
The dialog does not reflect modifying geometry which is different from drawing geometry. 
image

**Comment by simon-leech** [comment]
image
Pushed a commit to update the text to be relevant to geometry editing

**Comment by dbauszus-glx** [comment]
Looking good now.
image

**Review by dbauszus-glx — APPROVED** [review]

**Pull request merged**
