### PR TITLE
Dropdown : Reverse based upon page position

### PR DESCRIPTION
**Pull request by KieronFerrey**
This PR addresses an issue where when a dropdown element is at the bottom of the available viewport space - you cannot read the ul elements in it and/or they overspill off the page. 

This PR calculates the available space for the dropdown, and if its less than 150px, the dropdown has the `.reverse` class added to it so it opens upwards, to remove the issue. 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207389827168975

### CODE REVIEW

**Comment by simon-leech** [comment]
@KieronFerrey  I pushed a minor change just now. 
I rebuilt the CSS using the commands found here - https://github.com/GEOLYTIX/xyz/blob/main/DEVELOPING.md#esbuild

Also, when the space is less than 150px, I set the max height of the element to 150px (as its opening upwards). Previously it was being set as the available space below, which meant you could have a very small dropdown opening upwards. 


I think this is all good from my point of view now :)

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
This needs to wait until after the dropdown pills is merged since they are both making changes to the same module script.

**Comment by dbauszus-glx** [comment]
#1284 has now be merged and needs to be merged into this PR for testing.

**Comment by simon-leech** [comment]
I merged main and resolved merge issues.

**Review by simon-leech — APPROVED** [review]
Working as expected for me - when the space available is small the dropdown is reversed to open upwards

**Review by RobAndrewHurst — APPROVED** [review]
Nice one! looks all good to me @KieronFerrey

**Pull request merged**
