### PR TITLE
Style Parser : Change the default key message to detail which keys need changing

### PR DESCRIPTION
**Pull request by KieronFerrey**
# Pull Request Template

## Description

Included the object keys that violated the test in the warning message to easily understand what needs changing.

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Documentation

## How have you tested this? 
Tested using a style that violated the test, tested against a default style with no keys, one and two all of which behaved correctly.

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by simon-leech — APPROVED** [review]
This is fine to me - just a little improvement for fixing warnings :)
nice work!

**Comment by simon-leech** [comment]
I actually think we should update the styleparser tests with this change too, while we are here!

**Review by RobAndrewHurst — APPROVED** [review]
Approved!

**Comment by RobAndrewHurst** [comment]
Putting into draft until tests are updated

**Review by RobAndrewHurst — CHANGES_REQUESTED** [review]
Tests are not passing with how the style object should work

**Comment by RobAndrewHurst** [comment]
@simon-leech @KieronFerrey 

I have fixed the two hover and label tests to better suite the actual logic of the module. There is still an issue where the bogus key is not being removed from the style object. Let me know if you have any ideas.

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
this must wait until the other styleParser issues are resolved.

**Comment by simon-leech** [comment]
Closed as this PR has the same change in - #1331

**Pull request closed without merging**
