### PR TITLE
/ui/locations/entries/pin default_icon without a location.record property

### PR DESCRIPTION
**Pull request by simon-leech**
## Description

In a custom view, when calling ` mapp.ui.locations.infoj` - the location may not have a record. 
As such the `pin.mjs` would fail as it was looking for `entry.location.record.symbol`. 

This PR adds a check on this to prevent it.

## GitHub Issue

#1597 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ Updated Existing Tests
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by dbauszus-glx — APPROVED** [review]
Please see last comment.

**Review by simon-leech — COMMENTED** [review]
This is all working for me as expected

**Comment by dbauszus-glx** [comment]
The issue of undefined layer has been addressed in the geometry module.

A new location must not create an undefined layer.L to be pushed into the layers array.

**Comment by simon-leech** [comment]
Working for me - tested with a new location, created geometry, edited geometry, deleted geometry and all ok

**Pull request merged**
