### PR TITLE
Update Layer Test

### PR DESCRIPTION
**Pull request by simon-leech**
# Layer Test Fix and TLC

## Description

The Layer Test needed some TLC, comments have been added to explain the various stages of the test. 

The requirement for a geometry to be passed to the `newLocation` is valid. We provide either the `location.Pin` geometry, or just use the center of the mapview if there's no pin geometry.

The check on only deleting if `deleteLocation` is provided has been removed, we should always clear out locations generated in the test script.

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Testing

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ Updated Existing Tests
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
The integrity=true flag must be set in the URL params for the testview in order to test this.

**Review by dbauszus-glx — CHANGES_REQUESTED** [review]
I struggle reading through the execution of the layer.test.mjs

Is there a reason why the template paths and layer test are two seperate checks? Shouldn't the template paths be checked within the layer test?

I don't understand the delayFunction which is only used in the themes test.

Why is there a 1000ms required? That should be commented on.

```js
            for (const theme in layer.style.themes) {
              console.log(`Testing theme ${theme}`);
              layer.style.theme = layer.style.themes[theme];
              layer.reload();
              await delayFunction(1000);
            }
```

I don't understand the use of the default_zoom const. Can this be commented.

```js
const default_zoom = mapview.view?.z || 0
```

There is a lot of heavy nesting. At some points there are 10+ deep nestings where there is no way of knowing how deep I am when checking.

Some nesting can be resolved by using a `for of Object.getOwnPropertyNames` loop.

I don't understand this condition. This needs to be commented on. What's with maplibre and tiles format?

```js
if (!['maplibre', 'tiles'].includes(layer.format) && layer.infoj) {
```

Is it possible to put this whole location ? test into a function which is easier to read?

image

**Review by dbauszus-glx — APPROVED** [review]
I replaced the delay method with a one liner.

From my point this working and I understand what the tests are doing.

**Comment by RobAndrewHurst** [comment]
> I replaced the delay method with a one liner.
> 
> From my point this working and I understand what the tests are doing.

Nice thanks! I can see why it can be a one liner. 

Each to their own :)

**Pull request merged**
