### PR TITLE
layer query and templates

### PR DESCRIPTION
**Pull request by dbauszus-glx**
The geojson query template has been flagged as a layer query which requires a layer request parameter.

The getLayer method will attempt to retrieve a layer template from the templates if the layer param is not found in the locale.layers.

### CODE REVIEW

**Comment by dbauszus-glx** [comment]
I dismissed the security alert as not relevant. This should be addressed but not in this PR.

The issue is related to the params.user object which is assigned in the API method. User roles may be merged into a layer/template object and an error.message maybe returned from a failed query.

The security of the user object must be controlled in the API module which is yet to be tested and documented.

Message objects returned from failed requests should be escaped which may require a library. I will revise this in the relevant PR. https://github.com/GEOLYTIX/xyz/issues/1309

**Review by RobAndrewHurst — APPROVED** [review]
Very happy with this!

Added in a test to check for a template that does not have a layer param in the params!

**Review by AlexanderGeere — APPROVED** [review]
Ran integrity tests on an instance, checked reports. Looks good to me

**Comment by cityremade** [comment]
query endpoint is widely used to request data not related to a specific layer, such as non-spatial data based on location id.
How is this going to be supported?

**Review by cityremade — APPROVED** [review]
No objections;

**Pull request merged**
