### PR TITLE
Tabview Expanded more by Default

### PR DESCRIPTION
**Pull request by simon-leech**
Updated the _default.html so that the `tabview` is expanded by default more so that as a user you can see what it contains more easily without needing to drag it up. 

Before 
image

After
image

## GitHub Issue
#1631 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 
- ✅ New feature (non-breaking change which adds functionality)

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

### CODE REVIEW

**Review by dbauszus-glx — APPROVED** [review]
Excellent decision. First well with the MAPP logic to not have magic elements appearing _deus ex machina_.

**Review by RobAndrewHurst — CHANGES_REQUESTED** [review]
See the issue for comments of additional things we could potentially do :)

**Comment by dbauszus-glx** [comment]
@RobAndrewHurst please create a seperate issue for a request to add double click events to the resize handler. This PR solves the issue referenced in the ticket. We shouldnt make this more complicated and have it hanging around for longer than necessary.

**Review by AlexanderGeere — APPROVED** [review]
I like it! it would cool if in the future this could be configurable.

**Pull request merged**
